### ISSUE TITLE
Legacy keys coming from create?

### ISSUE THREAD

**Issue by NFollett89** [GoogleCloudPlatform/keyrotator#10]
https://github.com/GoogleCloudPlatform/keyrotator/blob/fdd7448f0e021056169cf7461c647971aa33ab19/keyrotator/iam_service.py#L73

It looks like the JSON keys created here are an older format.  When I try to authenticate to gcloud using the generated keys I get the following error:
`$ keyrotator create --project-id $PROJECT_ID --iam-account=$IAM_ACCOUNT --output-file test.json`
`$ gcloud auth activate-service-account --key-file=test.json`
> ERROR: (gcloud.auth.activate-service-account) The .json key file is not in a valid format.

If I create a key with gcloud and try activating:
`$ gcloud iam service-accounts keys create test.json --iam-account=$IAM_ACCOUNT`
> created key [REDACTED] of type [json] as [test.json] for [REDACTED]

`$ gcloud auth activate-service-account --key-file=test.json`
> Activated service account credentials for: [REDACTED]

**Comment by mirons-google** [comment]
Thanks @NFollett89 for opening the issue. Is supporting this new key format something you'd like to contribute to the project? We'll help you get the code reviewed and submitted, if so please you'll need to sign [Google's CLA](https://cla.developers.google.com/clas).

**Comment by NFollett89** [comment]
I've signed the CLA, I'll take a look into this from home later

**Comment by NFollett89** [comment]
It looks like `gcloud` and the API make 2 completely different formats of keys, x.509 vs. JWK respectively, and there's nothing that can be done from this layer to procure a key from the API which is accepted by `gcloud auth activate-service-account`.

With that said, I've no idea what I can do with the JWK the API produces.
